series: Basic OpenGL with GLFW
title: Skyboxes
author:
  name: David Erbelding
  email: daviderbelding@gmail.com
  github: https://github.com/Erbelding
description: Add textures to 3D geometry.
language: C++
tags:
  - Graphics
extra_resources:
  - title: An online tutorial explaining the process in depth.
    link: http://learnopengl.com/#!Advanced-OpenGL/Cubemaps
connections:
  - series: Basic OpenGL with GLFW
    title: Texturing a Cube